name: Continous Deployment
on: 
    push:
        branches: main
jobs:
    CD:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v4

          - name: Build Docker file 
            run: |
               docker build -t fullstack codebase/rdicidr-0.1.0/.
       
          - name: Push image to Docker Hub
            run: |
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker tag fullstack:latest satish680/fullstack:latest
              docker push satish680/fullstack:latest     