name: Continous Deployment
on: 
    push:
        branches: main
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v4
              