name: Continous Deployment
on: 
    push:
        branches: main
jobs:
    CD:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v4

          - name: Build Docker file 
            run: |
               docker build -t fullstack codebase/rdicidr-0.1.0/.
       
          - name: Push image to Docker Hub
            run: |
              echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
              docker tag fullstack:latest satish680/fullstack:latest
              docker push satish680/fullstack:latest  
              
          - name: Deploy to Minikube via SSH
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                cd /home/satish/fullstack/assessment-cc-devops-kubernetes-sr-01
                git pull
                minikube start --memory=2500
                kubectl apply -f custom/deployment.yaml
                kubectl apply -f custom/ingress.yaml    