name: Continous Integration
on: 
    push:
        branches: main
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v4        

          - name: Install dependencies
            run: yarn install  

          - name: Install node
            uses: actions/setup-node@v4
            with:
                node-version: '15'
                cache: 'yarn'  
                cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json    
                
          - name: Run ESLint
            run: yarn lint

          - name: Run Prettier
            run: yarn prettier

          - name: Run Jest tests
            run: CI=true yarn src/tests/test

          - name: Build project
            run: yarn build                
                
            
