name: Continous Integration
on: 
    push:
        branches: main
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v4         

          - name: Install node
            uses: actions/setup-node@v4
            with:
                node-version: '15'
                cache: 'npm'  
                cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json   
               
          - name: Install dependencies
            run: |
                cd codebase/rdicidr-0.1.0
                npm install                
