name: Continous Integration
on: 
    push:
        branches: main
jobs:
    CI:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/Checkout@v2        
            
          - name: Install node
            uses: actions/setup-node@v2
            with:
                node-version: '15'
                cache: 'npm'  
                cache-dependency-path: codebase/rdicidr-0.1.0/package-lock.json
          - name: Install dependencies
            run: npm install        
          
